### ISSUE TITLE
Add safety comments for unsafe portions of code.

### ISSUE THREAD

**Issue by Yossipossi1** [null8626/decancer#15]
See #14 for full comments.

Some portions utilize unsafe code to optimize performance. It would be useful for developers (current and future) if the purpose and invariants of the unsafe code were laid out in a comment to prevent violations.

**Comment by null8626** [comment]
Thank you for this, will do as soon as i can!

**Comment by null8626** [comment]
Is [this commit](https://github.com/null8626/decancer/commit/1cf07bf6e81e18f1b5729077aafb3794e61e35a4) enough? Because i think that's probably the only `unsafe` use here that has to do with user-generated input. The rest is pretty much related to the usage of the [internal codepoints binary](https://github.com/null8626/decancer/blob/main/core/bin/codepoints.bin), where the library obviously have no other choice than manually manage pointers.

**Comment by Yossipossi1** [comment]
Sure, those look good! I appreciate it! ^^

**Comment by null8626** [comment]
No problem! ❤️
